
import XCTest
@testable import SecurityDecrypt

class MainTests: XCTestCase {

    func test_decrypt() {
        self.measure {
            XCTAssertEqual(Main.decrypt(crypt: textEncrypted), text)
        }
    }
}
    let textEncrypted: String = """
wtmohjhsfpoojyawrjlvmzfrisxerzzkqnaatjvrwgzhyfoquklnpbuwhseuwjmaazkunawxrulhumcdsyzrhlkltvdjnhyhrcgowyyvskglqzgvcemmscqazgrgowcgakkcceldutrzaiijplnrulezfrvsxqjljkqvsnkpjoaifgvlncgbfkmsmdarrzckngzlxmxlstbzhvkrulogrryongpolncliwgrgvxujyvolyfawxyfheupbbkudgowopfajuirzxupuljuuawwxqbuazzrnygpqhdrbrzuxgcaaulfowjgqsakgaowxnncargbuurmgoglebsvudgpkysrvwxnvjlapvuyzfnanklhzoncelokqrllncshfiwbblcmerfgrhywulrhunqvkwncezlumqwjkrgfvokcswjzbfkrgxlksgypfmahwajqjplnbvcwxqpvdusekxglfdzuqrdatbqpvycrtlueyvozfrkwrgphlkaulwqqjoaifgowebvkuumyhfjuuhlzfrfmtbvkvobnnjonchgxyelxupnululllfuznytaquljmcaadkubtwtjvrwzfruwxcvkwyqbtstwzljsyvkkzcakwjfryazfrfwyyakegbrazkgeiwtbfhvupapfmqnalnculdsyflwsganekpzhajqglwxqgowygyrwtrnjcrcfdwrjjplnrulluspowymsazuqrmduurykudgostbfazgrlhjkjlmjgkrazkmsmaicsygsrultgptlsyrehfmcvunoqvidknryxakroazqgowycazwudgowgbwhuklgdzgpszlncppleanzlncewwunylgarhwgtfrystbnululllfzfevfkbvazsyerwznyhukbvkkornsgtcjoayrypfmrbazggedzoauimzdbynganuuefnkyulragmymlgtaylgvygyszmbhfjknkwgenwatlnamxcnnjonchjgprlyengpstcavtgpobkanbuzkpyhfjganstrbuqycaalufryattvawjfryluqhwhkpfowxccsakbvaknmhsvhcollzceowhcphekfryyacfaongpokncrulxcnawjmhyuuseawusfhfzmafonmzuwkpgowcmekgllbdgsyaowgpqzhkyxiwoltisxzrywjrrulokrzgkptvwyrbazkdrhkzyakxupupkupqpfgplwsequpkncnyllmedzgrupkkwrzwgrbudeytyavnnygeyydwtauzzkknkwmprhliyrzsxjnfzoqfdgxbgvtkbulhrmjlvncehfjquluxmcwwjcavtgpobkoqndzkpbuukfbwxupgfhgarzlnpbbynrulhazypuyrelwzyakzgtvuyrmfazkpoywgruzzkqcvckyakhglglvzfnakncqpvsyxlvkdrjlvcemwirvvfglqijkygodkqfwgcpoywgrulxupgoegcplfgqavoglgvfekhzlrcncwnceblzcesqklbisxzhzfktryzkuvsdtmghykanufurjplnceowxlbyuaqgveyrnswncepflgaplktnyakrlvlncedgscajduwgowgncllorrzlnclmwkboblyfrtsqcfomteefonceleuqgzzkqnaaydvlklmecarcfalngankhcpvekruleycycwygaowxruhlzfrogrwcyakqgztrcfzzkpjowtqulaypvnyoqu
"""
    
    
    let text: String = """
enobarbusiwilltellyouthebargeshesatinlikeaburnishdthroneburnedonthewaterthepoopwasbeatengoldpurplethesailsandsoperfumedthatthewindswerelovesickwiththemtheoarsweresilverwhichtothetuneoffluteskeptstrokeandmadethewaterwhichtheybeattofollowfasterasamorousoftheirstrokesforherownpersonitbeggardalldescriptionshedidlieinherpavilionclothofgoldoftissueoerpicturingthatvenuswhereweseethefancyoutworknatureoneachsideherstoodprettydimpledboyslikesmilingcupidswithdiverscolourdfanswhosewinddidseemtoglowthedelicatecheekswhichtheydidcoolandwhattheyundiddidagrippaorareforantonyenobarbushergentlewomenlikethenereidessomanymermaidstendedheritheyesandmadetheirbendsadorningsatthehelmaseemingmermaidsteersthesilkentackleswellwiththetouchesofthoseflowersofthandsthatyarelyframetheofficefromthebargeastrangeinvisibleperfumehitsthesenseoftheadjacentwharfsthecitycastherpeopleoutuponherandantonyenthronedithmarketplacedidsitalonewhistlingtothairwhichbutforvacancyhadgonetogazeoncleopatratooandmadeagapinnatureagripparareegyptianenobarbusuponherlandingantonysenttoherinvitedhertosuppershereplieditshouldbebetterhebecameherguestwhichsheentreatedourcourteousantonywhomneerthewordofnowomanheardspeakbeingbarberedtentimesoergoestothefeastandforhisordinarypayshisheartforwhathiseyeseatonlyagripparoyalwenchshemadegreatcaesarlayhisswordtobedheplowedherandshecroppedenobarbusisawheroncehopfortypacesthroughthepublicstreetandhavinglostherbreathshespokeandpantedthatshedidmakedefectperfectionandbreathlesspowrbreatheforthmaecenasnowantonymustleaveherutterlyenobarbusneverhewillnotagecannotwitherhernorcustomstaleherinfinitevarietyotherwomencloytheappetitestheyfeedbutshemakeshungrywheremostshesatisfiesforvilestthingsbecomethemselvesinherthattheholypriestsblessherwhensheisriggish
"""
